### ISSUE TITLE
Bossbar倒计时出现问题

### ISSUE THREAD

**Issue by xiaonian233** [julyss2019/JulySafe#3]
版本为：
![Snipaste_2021-09-06_23-15-45](https://user-images.githubusercontent.com/21072615/132237785-993fab22-7ec1-4575-adc8-761a416a2ae6.png)
问题为：
![Snipaste_2021-09-06_23-15-38](https://user-images.githubusercontent.com/21072615/132237819-efafa1d5-9dfd-403a-ae50-35e93bff6951.png)
掉落物倒计时异常
其它功能均正常，希望作者能看看

**Comment by julyss2019** [comment]
下个版本修复
