### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by HurryBy** [julyss2019/JulySafe#4]
C:\Users\Hurry\Downloads\Compressed\JulySafe-master>gradle clean shadowJar

> Task :compileJava FAILED
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\config\WorldFilter.java:12: 错误: 编码 GBK 的不可映射字符 (0x8C)
     * 鏄惁涓虹洰鏍囦笘鐣?
                 ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\config\WorldFilter.java:14: 错误: 编码 GBK 的不可映射字符 (0x8D)
     * @param regexWorlds 姝ｅ垯涓栫晫鍚?
                                 ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\executor\countdown\CountdownNotifier.java:45: 错误: 编码 GBK 的不可映射字符 (0x80)
     * 鎬诲?掕鏃剁鏁? 锛?1-10,30,60锛? return 60
         ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\executor\countdown\CountdownNotifier.java:45: 错误: 编码 GBK 的不可映射字符 (0xB0)
     * 鎬诲?掕鏃剁鏁? 锛?1-10,30,60锛? return 60
                ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\executor\countdown\CountdownNotifier.java:45: 错误: 编码 GBK 的不可映射字符 (0x88)
     * 鎬诲?掕鏃剁鏁? 锛?1-10,30,60锛? return 60
                   ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\executor\countdown\CountdownNotifier.java:45: 错误: 编码 GBK 的不可映射字符 (0x89)
     * 鎬诲?掕鏃剁鏁? 锛?1-10,30,60锛? return 60
                               ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:45: 错误: 编码 GBK 的不可映射字符 (0x87)
        yaml.set("鏈厤缃枃浠剁敤浜庣粫杩? QuickShop(浣滆??: Ghost_chu) 妫?鏌?, 鏃犲疄闄呯敤閫?", true);
                               ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:45: 错误: 编码 GBK 的不可映射字符 (0x80)
        yaml.set("鏈厤缃枃浠剁敤浜庣粫杩? QuickShop(浣滆??: Ghost_chu) 妫?鏌?, 鏃犲疄闄呯敤閫?", true);
                                             ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:45: 错误: 编码 GBK 的不可映射字符 (0x85)
        yaml.set("鏈厤缃枃浠剁敤浜庣粫杩? QuickShop(浣滆??: Ghost_chu) 妫?鏌?, 鏃犲疄闄呯敤閫?", true);
                                              ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:45: 错误: 编码 GBK 的不可映射字符 (0x80)
        yaml.set("鏈厤缃枃浠剁敤浜庣粫杩? QuickShop(浣滆??: Ghost_chu) 妫?鏌?, 鏃犲疄闄呯敤閫?", true);
                                                             ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:45: 错误: 编码 GBK 的不可映射字符 (0xA5)
        yaml.set("鏈厤缃枃浠剁敤浜庣粫杩? QuickShop(浣滆??: Ghost_chu) 妫?鏌?, 鏃犲疄闄呯敤閫?", true);
                                                               ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:45: 错误: 编码 GBK 的不可映射字符 (0x94)
        yaml.set("鏈厤缃枃浠剁敤浜庣粫杩? QuickShop(浣滆??: Ghost_chu) 妫?鏌?, 鏃犲疄闄呯敤閫?", true);
                                                                         ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:62: 错误: 编码 GBK 的不可映射字符 (0xBD)
            throw new RuntimeException("鍓嶇疆鎻掍欢 JulyLibrary 鏈姞杞?");
                                                               ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:97: 错误: 编码 GBK 的不可映射字符 (0x80)
        pluginLogger.info("&f浣滆??: 鏌? 鏈?, QQ: 884633197.");
                               ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:97: 错误: 编码 GBK 的不可映射字符 (0x85)
        pluginLogger.info("&f浣滆??: 鏌? 鏈?, QQ: 884633197.");
                                ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:97: 错误: 编码 GBK 的不可映射字符 (0x92)
        pluginLogger.info("&f浣滆??: 鏌? 鏈?, QQ: 884633197.");
                                    ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:97: 错误: 编码 GBK 的不可映射字符 (0x88)
        pluginLogger.info("&f浣滆??: 鏌? 鏈?, QQ: 884633197.");
                                       ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:98: 错误: 编码 GBK 的不可映射字符 (0xB5)
        pluginLogger.info("&f鐖卞彂鐢?: https://afdian.net/@july_ss");
                                 ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:99: 错误: 编码 GBK 的不可映射字符 (0x80)
        pluginLogger.info("&f涓嬭浇鏈?鏂扮増鏈?, 鑾峰彇鎶?鏈敮鎸佽鍔犲叆 QQ 鍞悗缇わ紙鍙戠數鍚庡叆缇わ級: 1148417878.");
                                 ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:99: 错误: 编码 GBK 的不可映射字符 (0xAC)
        pluginLogger.info("&f涓嬭浇鏈?鏂扮増鏈?, 鑾峰彇鎶?鏈敮鎸佽鍔犲叆 QQ 鍞悗缇わ紙鍙戠數鍚庡叆缇わ級: 1148417878.");
                                      ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:99: 错误: 编码 GBK 的不可映射字符 (0x80)
        pluginLogger.info("&f涓嬭浇鏈?鏂扮増鏈?, 鑾峰彇鎶?鏈敮鎸佽鍔犲叆 QQ 鍞悗缇わ紙鍙戠數鍚庡叆缇わ級: 1148417878.");
                                             ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:100: 错误: 编码 GBK 的不可映射字符 (0x95)
        pluginLogger.info("&f鎻掍欢鍒濆鍖栧畬姣?.");
                                       ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\JulySafe.java:121: 错误: 编码 GBK 的不可映射字符 (0xBD)
        pluginLogger.info("鎻掍欢琚嵏杞?.");
                                  ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\listeners\QuickShopBugFixListener.java:30: 错误: 编码 GBK 的不可映射字符 (0x80)
        Block upBlock = block.getRelative(0, 1, 0); // 涓婇潰涓?涓柟鍧?
                                                           ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\listeners\QuickShopBugFixListener.java:30: 错误: 编码 GBK 的不可映射字符 (0x97)
        Block upBlock = block.getRelative(0, 1, 0); // 涓婇潰涓?涓柟鍧?
                                                                ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\matcher\entity\impl\CustomNameEntityMatcher.java:14: 错误: 编码 GBK 的不可映射字符 (0x8D)
 * 鍖归厤灞曠ず鍚?
          ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\matcher\entity\impl\CustomNameEntityMatcher.java:49: 错误: 编码 GBK 的不可映射字符 (0xB2)
        // 鐗瑰埆娉ㄦ剰锛屾病鍚嶅瓧鍙兘鏄┖瀛楃涓?
                                 ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\Messager.java:17: 错误: 编码 GBK 的不可映射字符 (0x80)
 * 娑堟伅鍙戦?佺被
        ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\redstone\impl\ChunkRuntimeRedstoneChecker.java:174: 错误: 编码 GBK 的不可映射字符 (0xA0)
        // 鍚岀涓嶉噸澶嶇疮鍔?
                     ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\tasks\TpsTask.java:37: 错误: 编码 GBK 的不可映射字符 (0xBB)
        // 鎬? tick / seconds = tps锛坱icks per second锛屾瘡绉掕兘澶勭悊鍑犱釜tick锛?
            ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\tasks\TpsTask.java:37: 错误: 编码 GBK 的不可映射字符 (0x89)
        // 鎬? tick / seconds = tps锛坱icks per second锛屾瘡绉掕兘澶勭悊鍑犱釜tick锛?
                                                                    ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\tasks\TpsTask.java:38: 错误: 编码 GBK 的不可映射字符 (0x92)
        // 20 tick, 1绾崇 = 1e9绉?
                               ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\yaml\EasySection.java:88: 错误: 编码 GBK 的不可映射字符 (0x80)
     * 鑾峰彇褰撳墠璺緞涓嬬殑鎵?鏈夊瓙鑺傜偣
                    ^
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\scheduler\Scheduler.java:9: 错误: 程序包org.omg.PortableServer不存在
import org.omg.PortableServer.THREAD_POLICY_ID;
                             ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by julyss2019** [comment]
https://cloud.tencent.com/developer/article/1992070

**Comment by HurryBy** [comment]
> Task :compileJava FAILED
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\scheduler\Scheduler.java:9: 错误: 程序包org.omg.PortableServer不存在
import org.omg.PortableServer.THREAD_POLICY_ID;
                             ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 2 executed
