### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by HurryBy** [julyss2019/JulySafe#5]
> Task :compileJava FAILED
C:\Users\Hurry\Downloads\Compressed\JulySafe-master\src\main\java\com\github\julyss2019\bukkit\plugins\julysafe\scheduler\Scheduler.java:9: 错误: 程序包org.omg.PortableServer不存在
import org.omg.PortableServer.THREAD_POLICY_ID;
                             ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 2 executed

**Comment by julyss2019** [comment]
意外导入了那个包，删掉就可以了

**Comment by julyss2019** [comment]
> 意外导入了那个包，删掉就可以了

最新版本已修复
